### ISSUE TITLE
Merging client app 

### ISSUE THREAD

**Issue by dmitry-erin** [tiiuae/vmd#10]
Merging client app to the vmd repo as it was proposed on the Monday's meeting

**Comment by dmitry-erin** [comment]
During the googling how to clone one remote repo to another I ran into the better way: create submodule. 
What do you think?

**Comment by juliuskoskela** [comment]
I suggest we just copy the code and merge in one pull request directly in the Repo. Submodules are a pain in the butt...

**Comment by juliuskoskela** [comment]
We discussed this elsewhere and came to the conclusion that maybe we want a separate repo for the client.
