### ISSUE TITLE
Mutual TLS boostrapping

### ISSUE THREAD

**Issue by juliuskoskela** [tiiuae/vmd#12]
## Overview

There has been concern about how we manage bootstrapping TLS secret keys for client and server in a secure way. Let's build on this issue with discussion and research on the topic. This is important since it will have ramifications for which frameworks etc. we choose on server side.

## Breakdown

- [x] High level overview of the problem. Why is this non trivial? Do we have existing solutions?
- [x] Comparison analysis on different ways to solve the problem.
- [x] Implementation specification.

# Deliverables

- Input to high level design document.
- Relevant information to assess tools and frameworks against this requirement.

**Comment by vilvo** [comment]
In general - the secrets bootstrapping is both important topic and scoped out in our concept development. 

I'll start with important - in any operational context with security and risk management in mind - even a personal development laptop - it is important to pay attention how secrets are generated, stored, used, revoked and regenerated. This is the operational context. One can go all the way to establish secure boot with hardware backed root of trust, signing bootables and executables, securely attesting the boot and only then trusting the system, generating the secrets (certs or key-pairs) in air-gapped environments and provisioning them securely in distributed systems etc. We intentionally scope those out **to user**. That's a common practice with any secure system, **the user decides the acceptable risk levels and mitigations**. The other extreme is to leave everything open to make things easy. Now that that's out of the way, let's look how we can focus on the functional development of mutual TLS concept.

Let's then look at mutual TLS concept development scope. Functionally, for us it's enough to be able to generate the mutual TLS certificates using the component tooling and openly share the test certificates. This makes the concept development and verification much easier. We don't yet know if our initially designed component selection will support the mutual TLS at the level it's claimed so it makes sense to test it. In a testing and demo system, the secrets bootstrapping does not matter. In a demo system, there's operationally nothing to protect. More important for now is to focus on validating the design. To check if we can establish:
- client-server authentication using mutual TLS. Also, to ensure any non-authenticated client cannot establish TLS to server.
- after successful authentication, TLS encrypts the communication between client and server to protect the confidentiality.

If both work with test certificates, we can validate the design under certain threat model scenarios. At that point, it's up to **user** to securely bootstrap the system when being taken into use. We can obviously support that part by guiding the user and ensure no system gets unintentionally deployed with the openly shared test certificates.

If not, we need to revisit the design and look for some other solutions or change the design. Optional designs are to have a SSH tunnel (mutually authenticated and encrypted - always works) and pipe the REST API traffic in the tunnel uncrypted. Or VPN. In essence, both SSH and VPN have the same secrets management requirement from the user.

**Comment by juliuskoskela** [comment]
Thanks @vilvo just to summarize:

- TLS boostrapping is out of our scope as it is up to the user.
- We will provide the necessary tools for mutual TLS.
- We will continue testing the frameworks and validating the design from this perspective.
- "Functionally, for us it's enough to be able to generate the mutual TLS certificates using the component tooling and openly share the test certificates."
