### ISSUE TITLE
Configure build system and dependencies using Nix

### ISSUE THREAD

**Issue by juliuskoskela** [tiiuae/vmd#36]
# Overview

Vmd is a component of the [Ghaf-system](https://github.com/tiiuae/ghaf) which is built and configured using the [Nix](https://nixos.wiki/) package manager or operating system. We need to be able to build vmd as part of the Ghaf using the same Nix-system. This requires defining a `flake.nix` file which defines dependencies and interfaces with build scripts for the project.

# Breakdown

- [x] #41
- [x] Define `flake.nix` in the root of the repository which implements building `vmd`.

# Deliverables

- A `flake.nix` file at the root of the repository.
- Build (pure, reproducable) on ghaf after cloning the vmd-repository.

**Comment by vilvo** [comment]
Deliverables - must build (pure, reproducable) on ghaf after cloning the `vmd`-repository.

**Comment by juliuskoskela** [comment]
Resolved in https://github.com/tiiuae/vmd/pull/40
