### ISSUE TITLE
Implement vmd-client-cli

### ISSUE THREAD

**Issue by juliuskoskela** [tiiuae/vmd#39]
## Overview

We implement a program called `vmd-client-cli` which encapsulates client side access to vmd's REST API. This program will be used for Ghaf development, tests and CI as well as the `vmd-client` GUI-application. It acts as a layer that takes care of the mutual TLS connection between `vmd-server` and any client access such as a GUI-application or a shell script.

## Implementation proposal

- `vmd-client-cli` has a configuration file called `vmd-client.toml`. This file contains the configurations for client-cert, client-key, certificate-authority and base-URL. Config location can be set as environment variable `VMD_CLIENT_CONFIG_PATH=<path/>` or given as an argument using `--config <path/>`. All config options can be given as optional CLI parameters instead of a config file.
- `vmd-client-cli` takes a single argument as a path variable such as `vmd-client-cli vm/info/{ID}` and executes the request.
- Output formatting can have several options as flags such as `--json, --xml --deser`.
- By default outputs to stdout, but has optional `--output <path/>` argument.
- Timeout after 1 second if server hangs.

I propose that we implement the client with a simple CLI that takes in a path that corresponds to paths defined in the `vmd-api/openapi.yaml`. The REST API is well documented and building an additional API layer on top of it by enumerating all the API options in the CLI would be additional development overhead and possibly require significant refactoring when API is changed.

## Examples

```
> vmd-client-cli vm/list --json
{
    active-vms: [
        "1",
        "2",
    ]
}
```

**Comment by dmitry-erin** [comment]
So, to clarify how the communication between clients works: GUI client app should run the CLI client with argument (which is the path from api spec) to get the data?

**Comment by juliuskoskela** [comment]
> So, to clarify how the communications between clients works: GUI client app should run the CLI client with argument (which is the path from api spec) to get the data?

That's it in a nutshell. What do you think?

**Comment by dmitry-erin** [comment]
> > So, to clarify how the communications between clients works: GUI client app should run the CLI client with argument (which is the path from api spec) to get the data?
> 
> That's it in a nutshell. What do you think?

It is OK for me. The simpler the better. It resolves your issues and doesn't complicate my work.

**Comment by juliuskoskela** [comment]
There might be a use-case in which user wants to poll the server several times (possibly with a time interval) with a command such as `--poll <times>`.
