### ISSUE TITLE
Commit message looks funny.

### ISSUE THREAD

**Issue by vilvo** [tiiuae/vmd#5]
Commit message looks funny.

![screencapture](https://user-images.githubusercontent.com/1027150/220642047-78e285a1-ad33-4744-a355-79a7bae73176.png)
...

Also, please configure signing commits with `git commit -S` - see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
I use SSH signing but others prefer GPG.

Please use short commit header, separate commit body and DCO on a separate line. Let's commitlint those with GHA later.

**Comment by juliuskoskela** [comment]
Commit settings updated.

**Comment by vilvo** [comment]
There was still checks missing from the repository settings, let's leave it open.
I just added DCO check for the Web changes. And the GHA commit lint checks are still not done.
![screencapture](https://user-images.githubusercontent.com/1027150/221195983-ff2b5adf-f30c-4bd6-bdb9-8b7ab3dc3012.png)

**Comment by vilvo** [comment]
Also added branch protection rule to `main` - verified commits only from now on.
![screencapture](https://user-images.githubusercontent.com/1027150/221196699-30935ab8-b1e4-41d0-9797-3cf59fe02b77.png)
