### ISSUE TITLE
Protocol between the server and clients sides

### ISSUE THREAD

**Issue by baz2142** [tiiuae/vmd#6]
## Overview

The protocol to able to communicate the server and clients sides. Uses OpenAPI as basis, using generation feature to implement communication between endpoints

Reasons to use OpenAPI:
- Meets requirements: RESTful, API generator supports C++/Qt for the client and Rust for the server sides with TLS support
- Language-agnostic. Clients can understand and consume services without knowledge of server implementation or access to the server code
- Applications implemented based on OpenAPI interface files can automatically generate documentation of methods, parameters and models. This helps keep the documentation, client libraries and source code in sync

## Breakdown

- [x] #15
- [x] #16
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21

**Comment by juliuskoskela** [comment]
This seems like the best maintained crate for openapi on rust https://crates.io/crates/openapiv3

But...

This crate provides data structures that represent the [OpenAPI v3.0.x specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md). Note this does not cover OpenAPI v3.1 which was an incompatible change.

Should we use 3.0.x?

There's also https://crates.io/crates/okapi and https://crates.io/crates/rocket_okapi which weirldy point to the same repo https://github.com/GREsau/okapi.

Same as openapiv3: Supported OpenAPI Spec: [3.0.0](https://spec.openapis.org/oas/v3.0.0)
