### ISSUE TITLE
Minimum test for vmd-server

### ISSUE THREAD

**Issue by juliuskoskela** [tiiuae/vmd#7]
# Overview

Minimum test for creating vmd-server using rocket-rs. We want to be able to serve a REST-API endpoint that serves our test request. We implement mutual TLS authentication. As test data we use a request to check for kvm_api compatibility. The request will be served as a JSON string.

# Breakdown

- [x] Implement new repository structure that distinguishes between client, server, common and auth.
- [x] Create a Makefile that creates a certificate authority and client/server -side certificates using openssl.
- [x] Create request to check for kvm_compatibility.
- [x] Create REST-API test endpoint using rocket-rs.
- [x] Create a test script that tests the API with a GET request.

# Mutual TLS

Mutual TLS authentication is a process that ensures that traffic between entities is secure and trusted in both directions between a client and a server. It essentially takes place through a TLS handshake.

[Overview of mutual authentication](https://medium.com/weekly-webtips/how-to-generate-keys-for-mutual-tls-authentication-a90f53bcec64)

# Open questions

- Which key exchange or [cipher suite](https://en.wikipedia.org/wiki/Transport_Layer_Security#Key_exchange_or_key_agreement) do we use/support?

# Deliverables

- A Makefile that creates a certificate authority and client/server -side certificates using openssl.
- A rust program that spins an HTTPS server and serves the API endpoint at /.
- A test script that creates the certs, spins the server and tests the API via a GET request.

# References

https://medium.com/weekly-webtips/how-to-generate-keys-for-mutual-tls-authentication-a90f53bcec64
https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/
https://www.golinuxcloud.com/mutual-tls-authentication-mtls/
https://en.wikipedia.org/wiki/Transport_Layer_Security#Key_exchange_or_key_agreement
https://www.feistyduck.com/library/openssl-cookbook/online/openssl-command-line/recommended-suite-configuration.html
https://www.openssl.org/docs/man1.1.1/man1/ciphers.html
https://cabulous.medium.com/tls-1-2-andtls-1-3-handshake-walkthrough-4cfd0a798164
https://rocket.rs/v0.5-rc/guide/configuration/#mutual-tls

**Comment by vilvo** [comment]
On key exchange - as we are working on ghaf reference implementation, we can support the default rocket supported standard crypto as is. Rocket TLS 1.2 support should support DH and that would be more 1.3 future proof than RSA in key exchange. In practice, rocket supported and tested certificate do fine - https://github.com/SergioBenitez/Rocket/blob/v0.5-rc/examples/tls/private/gen_certs.sh

**Comment by baz2142** [comment]
> On key exchange - as we are working on ghaf reference implementation, we can support the default rocket supported standard crypto as is. Rocket TLS 1.2 support should support DH and that would be more 1.3 future proof than RSA in key exchange. In practice, rocket supported and tested certificate do fine - https://github.com/SergioBenitez/Rocket/blob/v0.5-rc/examples/tls/private/gen_certs.sh

We need to choose something not Rust-specific. As long as it Rocket working with not Rust-implementations -- good. We agreed we might possibly have different types of client: web apps as well.

As we also agreed protocol is my side of work, I'm looking for OpenAPI-based tools. OpenAPI has generator for both the client and the server sides for different languages: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/README.md
It will be wise to use this tools as it meets all our requirements

A have a little draft of the protocol in OpenAPI specification: https://github.com/baz2142/vmd/commit/723d0bd0a9985ca9bcee15d8a05aaec200ca42df

You can put the content here to visualise: https://editor.swagger.io/

**Comment by juliuskoskela** [comment]
> > On key exchange - as we are working on ghaf reference implementation, we can support the default rocket supported standard crypto as is. Rocket TLS 1.2 support should support DH and that would be more 1.3 future proof than RSA in key exchange. In practice, rocket supported and tested certificate do fine - https://github.com/SergioBenitez/Rocket/blob/v0.5-rc/examples/tls/private/gen_certs.sh
> 
> We need to choose something not Rust-specific. As long as it Rocket working with not Rust-implementations -- good. We agreed we might possibly have different types of client: web apps as well.
> 
> As we also agreed protocol is my side of work, I'm looking for OpenAPI-based tools. OpenAPI has generator for both the client and the server sides for different languages: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/README.md It will be wise to use this tools as it meets all our requirements
> 
> A have a little draft of the protocol in OpenAPI specification: [baz2142@723d0bd](https://github.com/baz2142/vmd/commit/723d0bd0a9985ca9bcee15d8a05aaec200ca42df)
> 
> You can put the content here to visualise: https://editor.swagger.io/

If both client and server support mutual TSL does the language matter really?

Good stuff on the OpenAPI, please update issue and create a PR so we can look at it and discuss.
